### ISSUE TITLE
Reference to undefined rule, missing spaces?

### ISSUE THREAD

**Issue by Rots** [simpl-dev/simpl#2]
Relevant part of my grammar

fragment Colon   :   ':';
fragment Digit  :   '0'..'9';
terminal TimeLiteral    : Digit Digit Colon Digit Digit  // MM:SS or HH:MM:SS  
;

When running the build script, gives me an error:
[...]
plugin-deps:
dependency:
require:
tool:
  [grammar] Generating parser from [..]\workspace\ExampleTest/src/tool/Example.spl to [..]\workspace\ExampleTest/target/gen/ee\cyber\simplicitas\example
  [grammar] error(106): [..]\workspace\ExampleTest/target/gen/ee\cyber\simplicitas\example/Example.g:139:6: reference to undefined rule: DigitDigitColonDigitDigit

If I change the TimeLiteral definition to:

terminal TimeLiteral   : (Digit) (Digit) (Colon) (Digit) (Digit)  // MM:SS or HH:MM:SS  
;

Then it works!

**Comment by margusf** [comment]
Committed fix SHA: 0fbc858ac9eb7e4d39fb5c194d93479edad17546

**Comment by margusf** [comment]
Fix released in 1.1.2

**Comment by Rots** [comment]
confirmed
