### ISSUE TITLE
Simple terminal rules as keywords

### ISSUE THREAD

**Issue by Rots** [simpl-dev/simpl#5]
with the following rule, the literal 'END' should be recognized as a keyword (and colored accordingly):

terminal End: 'END';

**Comment by Rots** [comment]
It should also recognize keywords in rules like:
terminal Bool : 'BOOL' | 'BOOLEAN';

**Comment by margusf** [comment]
The option rules pose a little problem. Currently keywords are string constants that are composed of characters. So, does the next rule represent keyword?

terminal Bool : 'BOOL' | '+++';

The "keywordness" can only be determined with granularity of the rule.

For simple rules, this is doable.

**Comment by margusf** [comment]
Fixed in bebd40c38cbdd032b738914faa4bcbe6c3d0aff5. Currently only works for simple rules where the terminal rule only contains one string literal.

terminal End: 'END';

More complex rules require quite complicated heuristics (and changes to Simpl internals).

**Comment by margusf** [comment]
Fix released as 1.1.2

**Comment by Rots** [comment]
works with simple rules
